// Code generated by mockery v2.53.3. DO NOT EDIT.

package drupalorg

import mock "github.com/stretchr/testify/mock"

// MockDrupalOrgService is an autogenerated mock type for the DrupalOrgService type
type MockDrupalOrgService struct {
	mock.Mock
}

type MockDrupalOrgService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDrupalOrgService) EXPECT() *MockDrupalOrgService_Expecter {
	return &MockDrupalOrgService_Expecter{mock: &_m.Mock}
}

// FindIssueNumber provides a mock function with given fields: text
func (_m *MockDrupalOrgService) FindIssueNumber(text string) (string, bool) {
	ret := _m.Called(text)

	if len(ret) == 0 {
		panic("no return value specified for FindIssueNumber")
	}

	var r0 string
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (string, bool)); ok {
		return rf(text)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(text)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(text)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockDrupalOrgService_FindIssueNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindIssueNumber'
type MockDrupalOrgService_FindIssueNumber_Call struct {
	*mock.Call
}

// FindIssueNumber is a helper method to define mock.On call
//   - text string
func (_e *MockDrupalOrgService_Expecter) FindIssueNumber(text interface{}) *MockDrupalOrgService_FindIssueNumber_Call {
	return &MockDrupalOrgService_FindIssueNumber_Call{Call: _e.mock.On("FindIssueNumber", text)}
}

func (_c *MockDrupalOrgService_FindIssueNumber_Call) Run(run func(text string)) *MockDrupalOrgService_FindIssueNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockDrupalOrgService_FindIssueNumber_Call) Return(_a0 string, _a1 bool) *MockDrupalOrgService_FindIssueNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDrupalOrgService_FindIssueNumber_Call) RunAndReturn(run func(string) (string, bool)) *MockDrupalOrgService_FindIssueNumber_Call {
	_c.Call.Return(run)
	return _c
}

// GetIssue provides a mock function with given fields: issueID
func (_m *MockDrupalOrgService) GetIssue(issueID string) (*Issue, error) {
	ret := _m.Called(issueID)

	if len(ret) == 0 {
		panic("no return value specified for GetIssue")
	}

	var r0 *Issue
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*Issue, error)); ok {
		return rf(issueID)
	}
	if rf, ok := ret.Get(0).(func(string) *Issue); ok {
		r0 = rf(issueID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Issue)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(issueID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDrupalOrgService_GetIssue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIssue'
type MockDrupalOrgService_GetIssue_Call struct {
	*mock.Call
}

// GetIssue is a helper method to define mock.On call
//   - issueID string
func (_e *MockDrupalOrgService_Expecter) GetIssue(issueID interface{}) *MockDrupalOrgService_GetIssue_Call {
	return &MockDrupalOrgService_GetIssue_Call{Call: _e.mock.On("GetIssue", issueID)}
}

func (_c *MockDrupalOrgService_GetIssue_Call) Run(run func(issueID string)) *MockDrupalOrgService_GetIssue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockDrupalOrgService_GetIssue_Call) Return(_a0 *Issue, _a1 error) *MockDrupalOrgService_GetIssue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDrupalOrgService_GetIssue_Call) RunAndReturn(run func(string) (*Issue, error)) *MockDrupalOrgService_GetIssue_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDrupalOrgService creates a new instance of MockDrupalOrgService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDrupalOrgService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDrupalOrgService {
	mock := &MockDrupalOrgService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
