// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rector

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRunner creates a new instance of MockRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRunner {
	mock := &MockRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRunner is an autogenerated mock type for the Runner type
type MockRunner struct {
	mock.Mock
}

type MockRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRunner) EXPECT() *MockRunner_Expecter {
	return &MockRunner_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockRunner
func (_mock *MockRunner) Run(ctx context.Context, dir string, customCodeDirectories []string) (ReturnOutput, error) {
	ret := _mock.Called(ctx, dir, customCodeDirectories)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 ReturnOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) (ReturnOutput, error)); ok {
		return returnFunc(ctx, dir, customCodeDirectories)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) ReturnOutput); ok {
		r0 = returnFunc(ctx, dir, customCodeDirectories)
	} else {
		r0 = ret.Get(0).(ReturnOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = returnFunc(ctx, dir, customCodeDirectories)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx
//   - dir
//   - customCodeDirectories
func (_e *MockRunner_Expecter) Run(ctx interface{}, dir interface{}, customCodeDirectories interface{}) *MockRunner_Run_Call {
	return &MockRunner_Run_Call{Call: _e.mock.On("Run", ctx, dir, customCodeDirectories)}
}

func (_c *MockRunner_Run_Call) Run(run func(ctx context.Context, dir string, customCodeDirectories []string)) *MockRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *MockRunner_Run_Call) Return(returnOutput ReturnOutput, err error) *MockRunner_Run_Call {
	_c.Call.Return(returnOutput, err)
	return _c
}

func (_c *MockRunner_Run_Call) RunAndReturn(run func(ctx context.Context, dir string, customCodeDirectories []string) (ReturnOutput, error)) *MockRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}
