// Code generated by mockery v2.53.3. DO NOT EDIT.

package rector

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRectorService is an autogenerated mock type for the RectorService type
type MockRectorService struct {
	mock.Mock
}

type MockRectorService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRectorService) EXPECT() *MockRectorService_Expecter {
	return &MockRectorService_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with given fields: ctx, dir, customCodeDirectories
func (_m *MockRectorService) Run(ctx context.Context, dir string, customCodeDirectories []string) (string, error) {
	ret := _m.Called(ctx, dir, customCodeDirectories)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) (string, error)); ok {
		return rf(ctx, dir, customCodeDirectories)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) string); ok {
		r0 = rf(ctx, dir, customCodeDirectories)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = rf(ctx, dir, customCodeDirectories)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRectorService_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockRectorService_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - customCodeDirectories []string
func (_e *MockRectorService_Expecter) Run(ctx interface{}, dir interface{}, customCodeDirectories interface{}) *MockRectorService_Run_Call {
	return &MockRectorService_Run_Call{Call: _e.mock.On("Run", ctx, dir, customCodeDirectories)}
}

func (_c *MockRectorService_Run_Call) Run(run func(ctx context.Context, dir string, customCodeDirectories []string)) *MockRectorService_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *MockRectorService_Run_Call) Return(_a0 string, _a1 error) *MockRectorService_Run_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRectorService_Run_Call) RunAndReturn(run func(context.Context, string, []string) (string, error)) *MockRectorService_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRectorService creates a new instance of MockRectorService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRectorService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRectorService {
	mock := &MockRectorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
