version: "2"
linters:
  enable:
    - revive
    - bodyclose
    - noctx
    - nilerr
    - testifylint
    - staticcheck
    - govet
    - errcheck
    - gosec
    - gocyclo
    - misspell
    - unconvert
    - unparam
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters: [gosec]
        path: _test\.go
        text: "G204|G702"
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
