with-expecter: true
packages:
  github.com/drupdater/drupdater:
    config:
      all: true
      dir: '{{.InterfaceDir}}'
      outpkg: '{{.PackageName}}'
      inpackage: true
      recursive: true

dir: mocks
outpkg: mocks
resolve-type-alias: false
issue-845-fix: true
