package updatecodingstyles

import (
	"context"
	"fmt"
	"os"
	"strings"
	"text/template"

	"github.com/drupdater/drupdater/internal"
	"github.com/drupdater/drupdater/internal/addon"
	"github.com/drupdater/drupdater/pkg/composer"
	"github.com/drupdater/drupdater/pkg/phpcs"

	"github.com/go-git/go-git/v5"
	"github.com/gookit/event"
	"go.uber.org/zap"
)

type UpdateCodingStyles struct {
	logger   *zap.Logger
	phpcs    phpcs.Runner
	config   internal.Config
	composer composer.Runner
}

func NewUpdateCodingStyles(logger *zap.Logger, phpcs phpcs.Runner, config internal.Config, composer composer.Runner) *UpdateCodingStyles {
	return &UpdateCodingStyles{
		logger:   logger,
		phpcs:    phpcs,
		config:   config,
		composer: composer,
	}
}

func (h *UpdateCodingStyles) SubscribedEvents() map[string]interface{} {
	return map[string]interface{}{
		"post-code-update": event.ListenerItem{
			Priority: event.Normal,
			Listener: event.ListenerFunc(h.postCodeUpdateHandler),
		},
	}
}

func (h *UpdateCodingStyles) RenderTemplate() (string, error) {
	return "", nil
}

var fileExists = func(path string) bool {

	if _, err := os.Stat(path + "/phpcs.xml"); os.IsNotExist(err) {
		if _, err := os.Stat(path + "/phpcs.xml.dist"); os.IsNotExist(err) {
			return false
		}
	}
	return true
}

func (h *UpdateCodingStyles) postCodeUpdateHandler(e event.Event) error {

	event := e.(*addon.PostCodeUpdateEvent)

	h.logger.Info("updating coding styles")

	if !fileExists(event.Path()) {
		created, err := h.CreatePHPCSConfig(event.Context(), event.Path(), event.Worktree())
		if err != nil {
			return err
		}
		if !created {
			h.logger.Debug("no phpcs.xml created, skipping coding style update")
			return nil
		}
	}

	if installed, _ := h.composer.IsPackageInstalled(event.Context(), event.Path(), "drupal/coder"); !installed {
		if err := h.InstallCoder(event.Context(), event.Path(), event.Worktree()); err != nil {
			return err
		}
	}

	codingStyleUpdateResult, err := h.phpcs.Run(event.Context(), event.Path())
	if err != nil {
		return fmt.Errorf("failed to run phpcs: %w", err)
	}

	if codingStyleUpdateResult.Totals.Fixable == 0 {
		h.logger.Debug("no coding style issues found")
		return nil
	}

	err = h.phpcs.RunCBF(event.Context(), event.Path())
	if err != nil {
		h.logger.Debug("remaining issues", zap.Error(err))
	}

	h.logger.Debug("adding files to commit", zap.Any("files", codingStyleUpdateResult.Files))

	for file := range codingStyleUpdateResult.Files {

		if (codingStyleUpdateResult.Files[file].Errors + codingStyleUpdateResult.Files[file].Warnings) == 0 {
			continue
		}
		relativePath := strings.TrimLeft(strings.TrimPrefix(file, event.Path()), "/")

		if _, err := event.Worktree().Add(relativePath); err != nil {
			return fmt.Errorf("failed to add file to commit: %w", err)
		}
	}

	_, err = event.Worktree().Commit("Update coding styles", &git.CommitOptions{})
	return err
}

func (h *UpdateCodingStyles) CreatePHPCSConfig(ctx context.Context, path string, worktree internal.Worktree) (bool, error) {
	h.logger.Debug("no phpcs.xml or phpcs.xml.dist file found, creating phpcs.xml")

	phpcsTemplate := `<?xml version="1.0" encoding="UTF-8"?>
<ruleset name="drupal-updater">
    <description>PHP CodeSniffer configuration generated by Drupal Updater</description>
    {{- range .Files }}
    <file>{{ . }}</file>
    {{- end }}
    <arg name="extensions" value="php,module,inc,install,test,profile,theme"/>
    <config name="drupal_core_version" value="{{ .Version }}"/>
    <rule ref="Drupal"/>
    <rule ref="DrupalPractice"/>
</ruleset>
`

	// Parse the template
	tmpl, err := template.New("ruleset").Parse(phpcsTemplate)
	if err != nil {
		panic(err)
	}

	// Create the output file
	outputFile, err := os.Create(path + "/phpcs.xml")
	if err != nil {
		panic(err)
	}

	drupalVersion, _ := h.composer.GetInstalledPackageVersion(ctx, path, "drupal/core")
	majorVersion := strings.Split(drupalVersion, ".")[0]

	data := struct {
		Files   []string
		Version string
	}{
		Files:   []string{},
		Version: majorVersion,
	}

	data.Files, err = h.composer.GetCustomCodeDirectories(ctx, path)
	if err != nil {
		return false, err
	}

	if len(data.Files) == 0 {
		h.logger.Debug("no custom code directories found, skipping coding style update")
		return false, nil
	}

	// Execute the template and write to the file
	err = tmpl.Execute(outputFile, data)
	if err != nil {
		panic(err)
	}

	outputFile.Close()

	if _, err := worktree.Add("phpcs.xml"); err != nil {
		return false, fmt.Errorf("failed to add file to commit: %w", err)
	}

	if _, err = worktree.Commit("Add PHPCS config", &git.CommitOptions{}); err != nil {
		return false, err
	}

	return true, nil
}

func (h *UpdateCodingStyles) InstallCoder(ctx context.Context, path string, worktree internal.Worktree) error {
	h.logger.Debug("drupal/coder is not installed, installing")
	if _, err := h.composer.Require(ctx, path, "--dev", "drupal/coder"); err != nil {
		return err
	}

	if err := worktree.AddGlob("composer.*"); err != nil {
		return fmt.Errorf("failed to add file to commit: %w", err)
	}
	if _, err := worktree.Commit("Install drupal/coder", &git.CommitOptions{}); err != nil {
		return err
	}

	return nil
}
