// Code generated by mockery v2.53.3. DO NOT EDIT.

package phpcs

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPhpCsService is an autogenerated mock type for the PhpCsService type
type MockPhpCsService struct {
	mock.Mock
}

type MockPhpCsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPhpCsService) EXPECT() *MockPhpCsService_Expecter {
	return &MockPhpCsService_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with given fields: ctx, dir
func (_m *MockPhpCsService) Run(ctx context.Context, dir string) (string, error) {
	ret := _m.Called(ctx, dir)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, dir)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, dir)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, dir)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPhpCsService_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockPhpCsService_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
func (_e *MockPhpCsService_Expecter) Run(ctx interface{}, dir interface{}) *MockPhpCsService_Run_Call {
	return &MockPhpCsService_Run_Call{Call: _e.mock.On("Run", ctx, dir)}
}

func (_c *MockPhpCsService_Run_Call) Run(run func(ctx context.Context, dir string)) *MockPhpCsService_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPhpCsService_Run_Call) Return(_a0 string, _a1 error) *MockPhpCsService_Run_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPhpCsService_Run_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockPhpCsService_Run_Call {
	_c.Call.Return(run)
	return _c
}

// RunCBF provides a mock function with given fields: ctx, dir
func (_m *MockPhpCsService) RunCBF(ctx context.Context, dir string) error {
	ret := _m.Called(ctx, dir)

	if len(ret) == 0 {
		panic("no return value specified for RunCBF")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, dir)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPhpCsService_RunCBF_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunCBF'
type MockPhpCsService_RunCBF_Call struct {
	*mock.Call
}

// RunCBF is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
func (_e *MockPhpCsService_Expecter) RunCBF(ctx interface{}, dir interface{}) *MockPhpCsService_RunCBF_Call {
	return &MockPhpCsService_RunCBF_Call{Call: _e.mock.On("RunCBF", ctx, dir)}
}

func (_c *MockPhpCsService_RunCBF_Call) Run(run func(ctx context.Context, dir string)) *MockPhpCsService_RunCBF_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPhpCsService_RunCBF_Call) Return(_a0 error) *MockPhpCsService_RunCBF_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPhpCsService_RunCBF_Call) RunAndReturn(run func(context.Context, string) error) *MockPhpCsService_RunCBF_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPhpCsService creates a new instance of MockPhpCsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPhpCsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPhpCsService {
	mock := &MockPhpCsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
