// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repo

import (
	"github.com/go-git/go-git/v5"
	"github.com/go-git/go-git/v5/plumbing"
	"github.com/go-git/go-git/v5/plumbing/object"
	"github.com/go-git/go-git/v5/plumbing/storer"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CommitObject provides a mock function for the type MockRepository
func (_mock *MockRepository) CommitObject(h plumbing.Hash) (*object.Commit, error) {
	ret := _mock.Called(h)

	if len(ret) == 0 {
		panic("no return value specified for CommitObject")
	}

	var r0 *object.Commit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(plumbing.Hash) (*object.Commit, error)); ok {
		return returnFunc(h)
	}
	if returnFunc, ok := ret.Get(0).(func(plumbing.Hash) *object.Commit); ok {
		r0 = returnFunc(h)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*object.Commit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(plumbing.Hash) error); ok {
		r1 = returnFunc(h)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CommitObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitObject'
type MockRepository_CommitObject_Call struct {
	*mock.Call
}

// CommitObject is a helper method to define mock.On call
//   - h
func (_e *MockRepository_Expecter) CommitObject(h interface{}) *MockRepository_CommitObject_Call {
	return &MockRepository_CommitObject_Call{Call: _e.mock.On("CommitObject", h)}
}

func (_c *MockRepository_CommitObject_Call) Run(run func(h plumbing.Hash)) *MockRepository_CommitObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(plumbing.Hash))
	})
	return _c
}

func (_c *MockRepository_CommitObject_Call) Return(commit *object.Commit, err error) *MockRepository_CommitObject_Call {
	_c.Call.Return(commit, err)
	return _c
}

func (_c *MockRepository_CommitObject_Call) RunAndReturn(run func(h plumbing.Hash) (*object.Commit, error)) *MockRepository_CommitObject_Call {
	_c.Call.Return(run)
	return _c
}

// Head provides a mock function for the type MockRepository
func (_mock *MockRepository) Head() (*plumbing.Reference, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Head")
	}

	var r0 *plumbing.Reference
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*plumbing.Reference, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *plumbing.Reference); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*plumbing.Reference)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Head_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Head'
type MockRepository_Head_Call struct {
	*mock.Call
}

// Head is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Head() *MockRepository_Head_Call {
	return &MockRepository_Head_Call{Call: _e.mock.On("Head")}
}

func (_c *MockRepository_Head_Call) Run(run func()) *MockRepository_Head_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Head_Call) Return(reference *plumbing.Reference, err error) *MockRepository_Head_Call {
	_c.Call.Return(reference, err)
	return _c
}

func (_c *MockRepository_Head_Call) RunAndReturn(run func() (*plumbing.Reference, error)) *MockRepository_Head_Call {
	_c.Call.Return(run)
	return _c
}

// Push provides a mock function for the type MockRepository
func (_mock *MockRepository) Push(o *git.PushOptions) error {
	ret := _mock.Called(o)

	if len(ret) == 0 {
		panic("no return value specified for Push")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*git.PushOptions) error); ok {
		r0 = returnFunc(o)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Push_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Push'
type MockRepository_Push_Call struct {
	*mock.Call
}

// Push is a helper method to define mock.On call
//   - o
func (_e *MockRepository_Expecter) Push(o interface{}) *MockRepository_Push_Call {
	return &MockRepository_Push_Call{Call: _e.mock.On("Push", o)}
}

func (_c *MockRepository_Push_Call) Run(run func(o *git.PushOptions)) *MockRepository_Push_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*git.PushOptions))
	})
	return _c
}

func (_c *MockRepository_Push_Call) Return(err error) *MockRepository_Push_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Push_Call) RunAndReturn(run func(o *git.PushOptions) error) *MockRepository_Push_Call {
	_c.Call.Return(run)
	return _c
}

// References provides a mock function for the type MockRepository
func (_mock *MockRepository) References() (storer.ReferenceIter, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for References")
	}

	var r0 storer.ReferenceIter
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (storer.ReferenceIter, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() storer.ReferenceIter); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(storer.ReferenceIter)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_References_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'References'
type MockRepository_References_Call struct {
	*mock.Call
}

// References is a helper method to define mock.On call
func (_e *MockRepository_Expecter) References() *MockRepository_References_Call {
	return &MockRepository_References_Call{Call: _e.mock.On("References")}
}

func (_c *MockRepository_References_Call) Run(run func()) *MockRepository_References_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_References_Call) Return(referenceIter storer.ReferenceIter, err error) *MockRepository_References_Call {
	_c.Call.Return(referenceIter, err)
	return _c
}

func (_c *MockRepository_References_Call) RunAndReturn(run func() (storer.ReferenceIter, error)) *MockRepository_References_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWorktree creates a new instance of MockWorktree. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorktree(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorktree {
	mock := &MockWorktree{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorktree is an autogenerated mock type for the Worktree type
type MockWorktree struct {
	mock.Mock
}

type MockWorktree_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorktree) EXPECT() *MockWorktree_Expecter {
	return &MockWorktree_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockWorktree
func (_mock *MockWorktree) Add(path string) (plumbing.Hash, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 plumbing.Hash
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (plumbing.Hash, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) plumbing.Hash); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plumbing.Hash)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorktree_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockWorktree_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - path
func (_e *MockWorktree_Expecter) Add(path interface{}) *MockWorktree_Add_Call {
	return &MockWorktree_Add_Call{Call: _e.mock.On("Add", path)}
}

func (_c *MockWorktree_Add_Call) Run(run func(path string)) *MockWorktree_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockWorktree_Add_Call) Return(hash plumbing.Hash, err error) *MockWorktree_Add_Call {
	_c.Call.Return(hash, err)
	return _c
}

func (_c *MockWorktree_Add_Call) RunAndReturn(run func(path string) (plumbing.Hash, error)) *MockWorktree_Add_Call {
	_c.Call.Return(run)
	return _c
}

// AddGlob provides a mock function for the type MockWorktree
func (_mock *MockWorktree) AddGlob(pattern string) error {
	ret := _mock.Called(pattern)

	if len(ret) == 0 {
		panic("no return value specified for AddGlob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(pattern)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWorktree_AddGlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddGlob'
type MockWorktree_AddGlob_Call struct {
	*mock.Call
}

// AddGlob is a helper method to define mock.On call
//   - pattern
func (_e *MockWorktree_Expecter) AddGlob(pattern interface{}) *MockWorktree_AddGlob_Call {
	return &MockWorktree_AddGlob_Call{Call: _e.mock.On("AddGlob", pattern)}
}

func (_c *MockWorktree_AddGlob_Call) Run(run func(pattern string)) *MockWorktree_AddGlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockWorktree_AddGlob_Call) Return(err error) *MockWorktree_AddGlob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWorktree_AddGlob_Call) RunAndReturn(run func(pattern string) error) *MockWorktree_AddGlob_Call {
	_c.Call.Return(run)
	return _c
}

// Checkout provides a mock function for the type MockWorktree
func (_mock *MockWorktree) Checkout(opts *git.CheckoutOptions) error {
	ret := _mock.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for Checkout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*git.CheckoutOptions) error); ok {
		r0 = returnFunc(opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWorktree_Checkout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Checkout'
type MockWorktree_Checkout_Call struct {
	*mock.Call
}

// Checkout is a helper method to define mock.On call
//   - opts
func (_e *MockWorktree_Expecter) Checkout(opts interface{}) *MockWorktree_Checkout_Call {
	return &MockWorktree_Checkout_Call{Call: _e.mock.On("Checkout", opts)}
}

func (_c *MockWorktree_Checkout_Call) Run(run func(opts *git.CheckoutOptions)) *MockWorktree_Checkout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*git.CheckoutOptions))
	})
	return _c
}

func (_c *MockWorktree_Checkout_Call) Return(err error) *MockWorktree_Checkout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWorktree_Checkout_Call) RunAndReturn(run func(opts *git.CheckoutOptions) error) *MockWorktree_Checkout_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function for the type MockWorktree
func (_mock *MockWorktree) Commit(msg string, opts *git.CommitOptions) (plumbing.Hash, error) {
	ret := _mock.Called(msg, opts)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 plumbing.Hash
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *git.CommitOptions) (plumbing.Hash, error)); ok {
		return returnFunc(msg, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *git.CommitOptions) plumbing.Hash); ok {
		r0 = returnFunc(msg, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plumbing.Hash)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *git.CommitOptions) error); ok {
		r1 = returnFunc(msg, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorktree_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockWorktree_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - msg
//   - opts
func (_e *MockWorktree_Expecter) Commit(msg interface{}, opts interface{}) *MockWorktree_Commit_Call {
	return &MockWorktree_Commit_Call{Call: _e.mock.On("Commit", msg, opts)}
}

func (_c *MockWorktree_Commit_Call) Run(run func(msg string, opts *git.CommitOptions)) *MockWorktree_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*git.CommitOptions))
	})
	return _c
}

func (_c *MockWorktree_Commit_Call) Return(hash plumbing.Hash, err error) *MockWorktree_Commit_Call {
	_c.Call.Return(hash, err)
	return _c
}

func (_c *MockWorktree_Commit_Call) RunAndReturn(run func(msg string, opts *git.CommitOptions) (plumbing.Hash, error)) *MockWorktree_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockWorktree
func (_mock *MockWorktree) Remove(path string) (plumbing.Hash, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 plumbing.Hash
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (plumbing.Hash, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) plumbing.Hash); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plumbing.Hash)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorktree_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockWorktree_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - path
func (_e *MockWorktree_Expecter) Remove(path interface{}) *MockWorktree_Remove_Call {
	return &MockWorktree_Remove_Call{Call: _e.mock.On("Remove", path)}
}

func (_c *MockWorktree_Remove_Call) Run(run func(path string)) *MockWorktree_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockWorktree_Remove_Call) Return(hash plumbing.Hash, err error) *MockWorktree_Remove_Call {
	_c.Call.Return(hash, err)
	return _c
}

func (_c *MockWorktree_Remove_Call) RunAndReturn(run func(path string) (plumbing.Hash, error)) *MockWorktree_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type MockWorktree
func (_mock *MockWorktree) Status() (git.Status, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 git.Status
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (git.Status, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() git.Status); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(git.Status)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorktree_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockWorktree_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
func (_e *MockWorktree_Expecter) Status() *MockWorktree_Status_Call {
	return &MockWorktree_Status_Call{Call: _e.mock.On("Status")}
}

func (_c *MockWorktree_Status_Call) Run(run func()) *MockWorktree_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWorktree_Status_Call) Return(status git.Status, err error) *MockWorktree_Status_Call {
	_c.Call.Return(status, err)
	return _c
}

func (_c *MockWorktree_Status_Call) RunAndReturn(run func() (git.Status, error)) *MockWorktree_Status_Call {
	_c.Call.Return(run)
	return _c
}
