// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package codehosting

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPlatform creates a new instance of MockPlatform. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlatform(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlatform {
	mock := &MockPlatform{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPlatform is an autogenerated mock type for the Platform type
type MockPlatform struct {
	mock.Mock
}

type MockPlatform_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlatform) EXPECT() *MockPlatform_Expecter {
	return &MockPlatform_Expecter{mock: &_m.Mock}
}

// CreateMergeRequest provides a mock function for the type MockPlatform
func (_mock *MockPlatform) CreateMergeRequest(ctx context.Context, title string, description string, sourceBranch string, targetBranch string) (MergeRequest, error) {
	ret := _mock.Called(ctx, title, description, sourceBranch, targetBranch)

	if len(ret) == 0 {
		panic("no return value specified for CreateMergeRequest")
	}

	var r0 MergeRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) (MergeRequest, error)); ok {
		return returnFunc(ctx, title, description, sourceBranch, targetBranch)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) MergeRequest); ok {
		r0 = returnFunc(ctx, title, description, sourceBranch, targetBranch)
	} else {
		r0 = ret.Get(0).(MergeRequest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, title, description, sourceBranch, targetBranch)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlatform_CreateMergeRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMergeRequest'
type MockPlatform_CreateMergeRequest_Call struct {
	*mock.Call
}

// CreateMergeRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - title string
//   - description string
//   - sourceBranch string
//   - targetBranch string
func (_e *MockPlatform_Expecter) CreateMergeRequest(ctx any, title any, description any, sourceBranch any, targetBranch any) *MockPlatform_CreateMergeRequest_Call {
	return &MockPlatform_CreateMergeRequest_Call{Call: _e.mock.On("CreateMergeRequest", ctx, title, description, sourceBranch, targetBranch)}
}

func (_c *MockPlatform_CreateMergeRequest_Call) Run(run func(ctx context.Context, title string, description string, sourceBranch string, targetBranch string)) *MockPlatform_CreateMergeRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockPlatform_CreateMergeRequest_Call) Return(mergeRequest MergeRequest, err error) *MockPlatform_CreateMergeRequest_Call {
	_c.Call.Return(mergeRequest, err)
	return _c
}

func (_c *MockPlatform_CreateMergeRequest_Call) RunAndReturn(run func(ctx context.Context, title string, description string, sourceBranch string, targetBranch string) (MergeRequest, error)) *MockPlatform_CreateMergeRequest_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBranch provides a mock function for the type MockPlatform
func (_mock *MockPlatform) DeleteBranch(ctx context.Context, branch string) error {
	ret := _mock.Called(ctx, branch)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBranch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, branch)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlatform_DeleteBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBranch'
type MockPlatform_DeleteBranch_Call struct {
	*mock.Call
}

// DeleteBranch is a helper method to define mock.On call
//   - ctx context.Context
//   - branch string
func (_e *MockPlatform_Expecter) DeleteBranch(ctx any, branch any) *MockPlatform_DeleteBranch_Call {
	return &MockPlatform_DeleteBranch_Call{Call: _e.mock.On("DeleteBranch", ctx, branch)}
}

func (_c *MockPlatform_DeleteBranch_Call) Run(run func(ctx context.Context, branch string)) *MockPlatform_DeleteBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlatform_DeleteBranch_Call) Return(err error) *MockPlatform_DeleteBranch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlatform_DeleteBranch_Call) RunAndReturn(run func(ctx context.Context, branch string) error) *MockPlatform_DeleteBranch_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type MockPlatform
func (_mock *MockPlatform) GetUser(ctx context.Context) (string, string) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 string
	var r1 string
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, string)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) string); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(string)
	}
	return r0, r1
}

// MockPlatform_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockPlatform_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPlatform_Expecter) GetUser(ctx any) *MockPlatform_GetUser_Call {
	return &MockPlatform_GetUser_Call{Call: _e.mock.On("GetUser", ctx)}
}

func (_c *MockPlatform_GetUser_Call) Run(run func(ctx context.Context)) *MockPlatform_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlatform_GetUser_Call) Return(name string, email string) *MockPlatform_GetUser_Call {
	_c.Call.Return(name, email)
	return _c
}

func (_c *MockPlatform_GetUser_Call) RunAndReturn(run func(ctx context.Context) (string, string)) *MockPlatform_GetUser_Call {
	_c.Call.Return(run)
	return _c
}
