// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	"context"

	"github.com/drupdater/drupdater/internal/addon"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWorkflowService creates a new instance of MockWorkflowService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkflowService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkflowService {
	mock := &MockWorkflowService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorkflowService is an autogenerated mock type for the WorkflowService type
type MockWorkflowService struct {
	mock.Mock
}

type MockWorkflowService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkflowService) EXPECT() *MockWorkflowService_Expecter {
	return &MockWorkflowService_Expecter{mock: &_m.Mock}
}

// StartUpdate provides a mock function for the type MockWorkflowService
func (_mock *MockWorkflowService) StartUpdate(ctx context.Context, strategy WorkflowStrategy, addons []addon.Addon) error {
	ret := _mock.Called(ctx, strategy, addons)

	if len(ret) == 0 {
		panic("no return value specified for StartUpdate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, WorkflowStrategy, []addon.Addon) error); ok {
		r0 = returnFunc(ctx, strategy, addons)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWorkflowService_StartUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartUpdate'
type MockWorkflowService_StartUpdate_Call struct {
	*mock.Call
}

// StartUpdate is a helper method to define mock.On call
//   - ctx
//   - strategy
//   - addons
func (_e *MockWorkflowService_Expecter) StartUpdate(ctx interface{}, strategy interface{}, addons interface{}) *MockWorkflowService_StartUpdate_Call {
	return &MockWorkflowService_StartUpdate_Call{Call: _e.mock.On("StartUpdate", ctx, strategy, addons)}
}

func (_c *MockWorkflowService_StartUpdate_Call) Run(run func(ctx context.Context, strategy WorkflowStrategy, addons []addon.Addon)) *MockWorkflowService_StartUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(WorkflowStrategy), args[2].([]addon.Addon))
	})
	return _c
}

func (_c *MockWorkflowService_StartUpdate_Call) Return(err error) *MockWorkflowService_StartUpdate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWorkflowService_StartUpdate_Call) RunAndReturn(run func(ctx context.Context, strategy WorkflowStrategy, addons []addon.Addon) error) *MockWorkflowService_StartUpdate_Call {
	_c.Call.Return(run)
	return _c
}
