// Code generated by mockery v2.53.3. DO NOT EDIT.

package utils

import mock "github.com/stretchr/testify/mock"

// MockCommandExecutor is an autogenerated mock type for the CommandExecutor type
type MockCommandExecutor struct {
	mock.Mock
}

type MockCommandExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommandExecutor) EXPECT() *MockCommandExecutor_Expecter {
	return &MockCommandExecutor_Expecter{mock: &_m.Mock}
}

// ConfigResave provides a mock function with given fields: dir, site
func (_m *MockCommandExecutor) ConfigResave(dir string, site string) error {
	ret := _m.Called(dir, site)

	if len(ret) == 0 {
		panic("no return value specified for ConfigResave")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(dir, site)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommandExecutor_ConfigResave_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfigResave'
type MockCommandExecutor_ConfigResave_Call struct {
	*mock.Call
}

// ConfigResave is a helper method to define mock.On call
//   - dir string
//   - site string
func (_e *MockCommandExecutor_Expecter) ConfigResave(dir interface{}, site interface{}) *MockCommandExecutor_ConfigResave_Call {
	return &MockCommandExecutor_ConfigResave_Call{Call: _e.mock.On("ConfigResave", dir, site)}
}

func (_c *MockCommandExecutor_ConfigResave_Call) Run(run func(dir string, site string)) *MockCommandExecutor_ConfigResave_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockCommandExecutor_ConfigResave_Call) Return(_a0 error) *MockCommandExecutor_ConfigResave_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommandExecutor_ConfigResave_Call) RunAndReturn(run func(string, string) error) *MockCommandExecutor_ConfigResave_Call {
	_c.Call.Return(run)
	return _c
}

// ExecComposer provides a mock function with given fields: dir, args
func (_m *MockCommandExecutor) ExecComposer(dir string, args ...string) (string, error) {
	_va := make([]interface{}, len(args))
	for _i := range args {
		_va[_i] = args[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, dir)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExecComposer")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, ...string) (string, error)); ok {
		return rf(dir, args...)
	}
	if rf, ok := ret.Get(0).(func(string, ...string) string); ok {
		r0 = rf(dir, args...)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, ...string) error); ok {
		r1 = rf(dir, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandExecutor_ExecComposer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecComposer'
type MockCommandExecutor_ExecComposer_Call struct {
	*mock.Call
}

// ExecComposer is a helper method to define mock.On call
//   - dir string
//   - args ...string
func (_e *MockCommandExecutor_Expecter) ExecComposer(dir interface{}, args ...interface{}) *MockCommandExecutor_ExecComposer_Call {
	return &MockCommandExecutor_ExecComposer_Call{Call: _e.mock.On("ExecComposer",
		append([]interface{}{dir}, args...)...)}
}

func (_c *MockCommandExecutor_ExecComposer_Call) Run(run func(dir string, args ...string)) *MockCommandExecutor_ExecComposer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockCommandExecutor_ExecComposer_Call) Return(_a0 string, _a1 error) *MockCommandExecutor_ExecComposer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandExecutor_ExecComposer_Call) RunAndReturn(run func(string, ...string) (string, error)) *MockCommandExecutor_ExecComposer_Call {
	_c.Call.Return(run)
	return _c
}

// ExecDrush provides a mock function with given fields: dir, site, args
func (_m *MockCommandExecutor) ExecDrush(dir string, site string, args ...string) (string, error) {
	_va := make([]interface{}, len(args))
	for _i := range args {
		_va[_i] = args[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, dir, site)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExecDrush")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, ...string) (string, error)); ok {
		return rf(dir, site, args...)
	}
	if rf, ok := ret.Get(0).(func(string, string, ...string) string); ok {
		r0 = rf(dir, site, args...)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, ...string) error); ok {
		r1 = rf(dir, site, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandExecutor_ExecDrush_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecDrush'
type MockCommandExecutor_ExecDrush_Call struct {
	*mock.Call
}

// ExecDrush is a helper method to define mock.On call
//   - dir string
//   - site string
//   - args ...string
func (_e *MockCommandExecutor_Expecter) ExecDrush(dir interface{}, site interface{}, args ...interface{}) *MockCommandExecutor_ExecDrush_Call {
	return &MockCommandExecutor_ExecDrush_Call{Call: _e.mock.On("ExecDrush",
		append([]interface{}{dir, site}, args...)...)}
}

func (_c *MockCommandExecutor_ExecDrush_Call) Run(run func(dir string, site string, args ...string)) *MockCommandExecutor_ExecDrush_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(string), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockCommandExecutor_ExecDrush_Call) Return(_a0 string, _a1 error) *MockCommandExecutor_ExecDrush_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandExecutor_ExecDrush_Call) RunAndReturn(run func(string, string, ...string) (string, error)) *MockCommandExecutor_ExecDrush_Call {
	_c.Call.Return(run)
	return _c
}

// ExportConfiguration provides a mock function with given fields: dir, site
func (_m *MockCommandExecutor) ExportConfiguration(dir string, site string) error {
	ret := _m.Called(dir, site)

	if len(ret) == 0 {
		panic("no return value specified for ExportConfiguration")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(dir, site)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommandExecutor_ExportConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportConfiguration'
type MockCommandExecutor_ExportConfiguration_Call struct {
	*mock.Call
}

// ExportConfiguration is a helper method to define mock.On call
//   - dir string
//   - site string
func (_e *MockCommandExecutor_Expecter) ExportConfiguration(dir interface{}, site interface{}) *MockCommandExecutor_ExportConfiguration_Call {
	return &MockCommandExecutor_ExportConfiguration_Call{Call: _e.mock.On("ExportConfiguration", dir, site)}
}

func (_c *MockCommandExecutor_ExportConfiguration_Call) Run(run func(dir string, site string)) *MockCommandExecutor_ExportConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockCommandExecutor_ExportConfiguration_Call) Return(_a0 error) *MockCommandExecutor_ExportConfiguration_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommandExecutor_ExportConfiguration_Call) RunAndReturn(run func(string, string) error) *MockCommandExecutor_ExportConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateDiffTable provides a mock function with given fields: path, targetBranch, withLinks
func (_m *MockCommandExecutor) GenerateDiffTable(path string, targetBranch string, withLinks bool) (string, error) {
	ret := _m.Called(path, targetBranch, withLinks)

	if len(ret) == 0 {
		panic("no return value specified for GenerateDiffTable")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, bool) (string, error)); ok {
		return rf(path, targetBranch, withLinks)
	}
	if rf, ok := ret.Get(0).(func(string, string, bool) string); ok {
		r0 = rf(path, targetBranch, withLinks)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, bool) error); ok {
		r1 = rf(path, targetBranch, withLinks)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandExecutor_GenerateDiffTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateDiffTable'
type MockCommandExecutor_GenerateDiffTable_Call struct {
	*mock.Call
}

// GenerateDiffTable is a helper method to define mock.On call
//   - path string
//   - targetBranch string
//   - withLinks bool
func (_e *MockCommandExecutor_Expecter) GenerateDiffTable(path interface{}, targetBranch interface{}, withLinks interface{}) *MockCommandExecutor_GenerateDiffTable_Call {
	return &MockCommandExecutor_GenerateDiffTable_Call{Call: _e.mock.On("GenerateDiffTable", path, targetBranch, withLinks)}
}

func (_c *MockCommandExecutor_GenerateDiffTable_Call) Run(run func(path string, targetBranch string, withLinks bool)) *MockCommandExecutor_GenerateDiffTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockCommandExecutor_GenerateDiffTable_Call) Return(_a0 string, _a1 error) *MockCommandExecutor_GenerateDiffTable_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandExecutor_GenerateDiffTable_Call) RunAndReturn(run func(string, string, bool) (string, error)) *MockCommandExecutor_GenerateDiffTable_Call {
	_c.Call.Return(run)
	return _c
}

// GetComposerAllowPlugins provides a mock function with given fields: dir
func (_m *MockCommandExecutor) GetComposerAllowPlugins(dir string) (map[string]bool, error) {
	ret := _m.Called(dir)

	if len(ret) == 0 {
		panic("no return value specified for GetComposerAllowPlugins")
	}

	var r0 map[string]bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (map[string]bool, error)); ok {
		return rf(dir)
	}
	if rf, ok := ret.Get(0).(func(string) map[string]bool); ok {
		r0 = rf(dir)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]bool)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(dir)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandExecutor_GetComposerAllowPlugins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComposerAllowPlugins'
type MockCommandExecutor_GetComposerAllowPlugins_Call struct {
	*mock.Call
}

// GetComposerAllowPlugins is a helper method to define mock.On call
//   - dir string
func (_e *MockCommandExecutor_Expecter) GetComposerAllowPlugins(dir interface{}) *MockCommandExecutor_GetComposerAllowPlugins_Call {
	return &MockCommandExecutor_GetComposerAllowPlugins_Call{Call: _e.mock.On("GetComposerAllowPlugins", dir)}
}

func (_c *MockCommandExecutor_GetComposerAllowPlugins_Call) Run(run func(dir string)) *MockCommandExecutor_GetComposerAllowPlugins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCommandExecutor_GetComposerAllowPlugins_Call) Return(_a0 map[string]bool, _a1 error) *MockCommandExecutor_GetComposerAllowPlugins_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandExecutor_GetComposerAllowPlugins_Call) RunAndReturn(run func(string) (map[string]bool, error)) *MockCommandExecutor_GetComposerAllowPlugins_Call {
	_c.Call.Return(run)
	return _c
}

// GetComposerConfig provides a mock function with given fields: dir, key
func (_m *MockCommandExecutor) GetComposerConfig(dir string, key string) (string, error) {
	ret := _m.Called(dir, key)

	if len(ret) == 0 {
		panic("no return value specified for GetComposerConfig")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(dir, key)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(dir, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(dir, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandExecutor_GetComposerConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComposerConfig'
type MockCommandExecutor_GetComposerConfig_Call struct {
	*mock.Call
}

// GetComposerConfig is a helper method to define mock.On call
//   - dir string
//   - key string
func (_e *MockCommandExecutor_Expecter) GetComposerConfig(dir interface{}, key interface{}) *MockCommandExecutor_GetComposerConfig_Call {
	return &MockCommandExecutor_GetComposerConfig_Call{Call: _e.mock.On("GetComposerConfig", dir, key)}
}

func (_c *MockCommandExecutor_GetComposerConfig_Call) Run(run func(dir string, key string)) *MockCommandExecutor_GetComposerConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockCommandExecutor_GetComposerConfig_Call) Return(_a0 string, _a1 error) *MockCommandExecutor_GetComposerConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandExecutor_GetComposerConfig_Call) RunAndReturn(run func(string, string) (string, error)) *MockCommandExecutor_GetComposerConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfigSyncDir provides a mock function with given fields: dir, site, relative
func (_m *MockCommandExecutor) GetConfigSyncDir(dir string, site string, relative bool) (string, error) {
	ret := _m.Called(dir, site, relative)

	if len(ret) == 0 {
		panic("no return value specified for GetConfigSyncDir")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, bool) (string, error)); ok {
		return rf(dir, site, relative)
	}
	if rf, ok := ret.Get(0).(func(string, string, bool) string); ok {
		r0 = rf(dir, site, relative)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, bool) error); ok {
		r1 = rf(dir, site, relative)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandExecutor_GetConfigSyncDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfigSyncDir'
type MockCommandExecutor_GetConfigSyncDir_Call struct {
	*mock.Call
}

// GetConfigSyncDir is a helper method to define mock.On call
//   - dir string
//   - site string
//   - relative bool
func (_e *MockCommandExecutor_Expecter) GetConfigSyncDir(dir interface{}, site interface{}, relative interface{}) *MockCommandExecutor_GetConfigSyncDir_Call {
	return &MockCommandExecutor_GetConfigSyncDir_Call{Call: _e.mock.On("GetConfigSyncDir", dir, site, relative)}
}

func (_c *MockCommandExecutor_GetConfigSyncDir_Call) Run(run func(dir string, site string, relative bool)) *MockCommandExecutor_GetConfigSyncDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockCommandExecutor_GetConfigSyncDir_Call) Return(_a0 string, _a1 error) *MockCommandExecutor_GetConfigSyncDir_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandExecutor_GetConfigSyncDir_Call) RunAndReturn(run func(string, string, bool) (string, error)) *MockCommandExecutor_GetConfigSyncDir_Call {
	_c.Call.Return(run)
	return _c
}

// GetCustomCodeDirectories provides a mock function with given fields: dir
func (_m *MockCommandExecutor) GetCustomCodeDirectories(dir string) ([]string, error) {
	ret := _m.Called(dir)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomCodeDirectories")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(dir)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(dir)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(dir)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandExecutor_GetCustomCodeDirectories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCustomCodeDirectories'
type MockCommandExecutor_GetCustomCodeDirectories_Call struct {
	*mock.Call
}

// GetCustomCodeDirectories is a helper method to define mock.On call
//   - dir string
func (_e *MockCommandExecutor_Expecter) GetCustomCodeDirectories(dir interface{}) *MockCommandExecutor_GetCustomCodeDirectories_Call {
	return &MockCommandExecutor_GetCustomCodeDirectories_Call{Call: _e.mock.On("GetCustomCodeDirectories", dir)}
}

func (_c *MockCommandExecutor_GetCustomCodeDirectories_Call) Run(run func(dir string)) *MockCommandExecutor_GetCustomCodeDirectories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCommandExecutor_GetCustomCodeDirectories_Call) Return(_a0 []string, _a1 error) *MockCommandExecutor_GetCustomCodeDirectories_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandExecutor_GetCustomCodeDirectories_Call) RunAndReturn(run func(string) ([]string, error)) *MockCommandExecutor_GetCustomCodeDirectories_Call {
	_c.Call.Return(run)
	return _c
}

// GetDrupalWebDir provides a mock function with given fields: dir
func (_m *MockCommandExecutor) GetDrupalWebDir(dir string) (string, error) {
	ret := _m.Called(dir)

	if len(ret) == 0 {
		panic("no return value specified for GetDrupalWebDir")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(dir)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(dir)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(dir)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandExecutor_GetDrupalWebDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDrupalWebDir'
type MockCommandExecutor_GetDrupalWebDir_Call struct {
	*mock.Call
}

// GetDrupalWebDir is a helper method to define mock.On call
//   - dir string
func (_e *MockCommandExecutor_Expecter) GetDrupalWebDir(dir interface{}) *MockCommandExecutor_GetDrupalWebDir_Call {
	return &MockCommandExecutor_GetDrupalWebDir_Call{Call: _e.mock.On("GetDrupalWebDir", dir)}
}

func (_c *MockCommandExecutor_GetDrupalWebDir_Call) Run(run func(dir string)) *MockCommandExecutor_GetDrupalWebDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCommandExecutor_GetDrupalWebDir_Call) Return(_a0 string, _a1 error) *MockCommandExecutor_GetDrupalWebDir_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandExecutor_GetDrupalWebDir_Call) RunAndReturn(run func(string) (string, error)) *MockCommandExecutor_GetDrupalWebDir_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstalledPackageVersion provides a mock function with given fields: dir, packageName
func (_m *MockCommandExecutor) GetInstalledPackageVersion(dir string, packageName string) (string, error) {
	ret := _m.Called(dir, packageName)

	if len(ret) == 0 {
		panic("no return value specified for GetInstalledPackageVersion")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(dir, packageName)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(dir, packageName)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(dir, packageName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandExecutor_GetInstalledPackageVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstalledPackageVersion'
type MockCommandExecutor_GetInstalledPackageVersion_Call struct {
	*mock.Call
}

// GetInstalledPackageVersion is a helper method to define mock.On call
//   - dir string
//   - packageName string
func (_e *MockCommandExecutor_Expecter) GetInstalledPackageVersion(dir interface{}, packageName interface{}) *MockCommandExecutor_GetInstalledPackageVersion_Call {
	return &MockCommandExecutor_GetInstalledPackageVersion_Call{Call: _e.mock.On("GetInstalledPackageVersion", dir, packageName)}
}

func (_c *MockCommandExecutor_GetInstalledPackageVersion_Call) Run(run func(dir string, packageName string)) *MockCommandExecutor_GetInstalledPackageVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockCommandExecutor_GetInstalledPackageVersion_Call) Return(_a0 string, _a1 error) *MockCommandExecutor_GetInstalledPackageVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandExecutor_GetInstalledPackageVersion_Call) RunAndReturn(run func(string, string) (string, error)) *MockCommandExecutor_GetInstalledPackageVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetTranslationPath provides a mock function with given fields: dir, site, relative
func (_m *MockCommandExecutor) GetTranslationPath(dir string, site string, relative bool) (string, error) {
	ret := _m.Called(dir, site, relative)

	if len(ret) == 0 {
		panic("no return value specified for GetTranslationPath")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, bool) (string, error)); ok {
		return rf(dir, site, relative)
	}
	if rf, ok := ret.Get(0).(func(string, string, bool) string); ok {
		r0 = rf(dir, site, relative)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, bool) error); ok {
		r1 = rf(dir, site, relative)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandExecutor_GetTranslationPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTranslationPath'
type MockCommandExecutor_GetTranslationPath_Call struct {
	*mock.Call
}

// GetTranslationPath is a helper method to define mock.On call
//   - dir string
//   - site string
//   - relative bool
func (_e *MockCommandExecutor_Expecter) GetTranslationPath(dir interface{}, site interface{}, relative interface{}) *MockCommandExecutor_GetTranslationPath_Call {
	return &MockCommandExecutor_GetTranslationPath_Call{Call: _e.mock.On("GetTranslationPath", dir, site, relative)}
}

func (_c *MockCommandExecutor_GetTranslationPath_Call) Run(run func(dir string, site string, relative bool)) *MockCommandExecutor_GetTranslationPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockCommandExecutor_GetTranslationPath_Call) Return(_a0 string, _a1 error) *MockCommandExecutor_GetTranslationPath_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandExecutor_GetTranslationPath_Call) RunAndReturn(run func(string, string, bool) (string, error)) *MockCommandExecutor_GetTranslationPath_Call {
	_c.Call.Return(run)
	return _c
}

// InstallDependencies provides a mock function with given fields: dir
func (_m *MockCommandExecutor) InstallDependencies(dir string) error {
	ret := _m.Called(dir)

	if len(ret) == 0 {
		panic("no return value specified for InstallDependencies")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(dir)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommandExecutor_InstallDependencies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallDependencies'
type MockCommandExecutor_InstallDependencies_Call struct {
	*mock.Call
}

// InstallDependencies is a helper method to define mock.On call
//   - dir string
func (_e *MockCommandExecutor_Expecter) InstallDependencies(dir interface{}) *MockCommandExecutor_InstallDependencies_Call {
	return &MockCommandExecutor_InstallDependencies_Call{Call: _e.mock.On("InstallDependencies", dir)}
}

func (_c *MockCommandExecutor_InstallDependencies_Call) Run(run func(dir string)) *MockCommandExecutor_InstallDependencies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCommandExecutor_InstallDependencies_Call) Return(_a0 error) *MockCommandExecutor_InstallDependencies_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommandExecutor_InstallDependencies_Call) RunAndReturn(run func(string) error) *MockCommandExecutor_InstallDependencies_Call {
	_c.Call.Return(run)
	return _c
}

// InstallPackages provides a mock function with given fields: dir, args
func (_m *MockCommandExecutor) InstallPackages(dir string, args ...string) (string, error) {
	_va := make([]interface{}, len(args))
	for _i := range args {
		_va[_i] = args[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, dir)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for InstallPackages")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, ...string) (string, error)); ok {
		return rf(dir, args...)
	}
	if rf, ok := ret.Get(0).(func(string, ...string) string); ok {
		r0 = rf(dir, args...)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, ...string) error); ok {
		r1 = rf(dir, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandExecutor_InstallPackages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallPackages'
type MockCommandExecutor_InstallPackages_Call struct {
	*mock.Call
}

// InstallPackages is a helper method to define mock.On call
//   - dir string
//   - args ...string
func (_e *MockCommandExecutor_Expecter) InstallPackages(dir interface{}, args ...interface{}) *MockCommandExecutor_InstallPackages_Call {
	return &MockCommandExecutor_InstallPackages_Call{Call: _e.mock.On("InstallPackages",
		append([]interface{}{dir}, args...)...)}
}

func (_c *MockCommandExecutor_InstallPackages_Call) Run(run func(dir string, args ...string)) *MockCommandExecutor_InstallPackages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockCommandExecutor_InstallPackages_Call) Return(_a0 string, _a1 error) *MockCommandExecutor_InstallPackages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandExecutor_InstallPackages_Call) RunAndReturn(run func(string, ...string) (string, error)) *MockCommandExecutor_InstallPackages_Call {
	_c.Call.Return(run)
	return _c
}

// InstallSite provides a mock function with given fields: dir, site
func (_m *MockCommandExecutor) InstallSite(dir string, site string) error {
	ret := _m.Called(dir, site)

	if len(ret) == 0 {
		panic("no return value specified for InstallSite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(dir, site)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommandExecutor_InstallSite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallSite'
type MockCommandExecutor_InstallSite_Call struct {
	*mock.Call
}

// InstallSite is a helper method to define mock.On call
//   - dir string
//   - site string
func (_e *MockCommandExecutor_Expecter) InstallSite(dir interface{}, site interface{}) *MockCommandExecutor_InstallSite_Call {
	return &MockCommandExecutor_InstallSite_Call{Call: _e.mock.On("InstallSite", dir, site)}
}

func (_c *MockCommandExecutor_InstallSite_Call) Run(run func(dir string, site string)) *MockCommandExecutor_InstallSite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockCommandExecutor_InstallSite_Call) Return(_a0 error) *MockCommandExecutor_InstallSite_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommandExecutor_InstallSite_Call) RunAndReturn(run func(string, string) error) *MockCommandExecutor_InstallSite_Call {
	_c.Call.Return(run)
	return _c
}

// IsModuleEnabled provides a mock function with given fields: dir, site, module
func (_m *MockCommandExecutor) IsModuleEnabled(dir string, site string, module string) (bool, error) {
	ret := _m.Called(dir, site, module)

	if len(ret) == 0 {
		panic("no return value specified for IsModuleEnabled")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (bool, error)); ok {
		return rf(dir, site, module)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) bool); ok {
		r0 = rf(dir, site, module)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(dir, site, module)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandExecutor_IsModuleEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsModuleEnabled'
type MockCommandExecutor_IsModuleEnabled_Call struct {
	*mock.Call
}

// IsModuleEnabled is a helper method to define mock.On call
//   - dir string
//   - site string
//   - module string
func (_e *MockCommandExecutor_Expecter) IsModuleEnabled(dir interface{}, site interface{}, module interface{}) *MockCommandExecutor_IsModuleEnabled_Call {
	return &MockCommandExecutor_IsModuleEnabled_Call{Call: _e.mock.On("IsModuleEnabled", dir, site, module)}
}

func (_c *MockCommandExecutor_IsModuleEnabled_Call) Run(run func(dir string, site string, module string)) *MockCommandExecutor_IsModuleEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockCommandExecutor_IsModuleEnabled_Call) Return(_a0 bool, _a1 error) *MockCommandExecutor_IsModuleEnabled_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandExecutor_IsModuleEnabled_Call) RunAndReturn(run func(string, string, string) (bool, error)) *MockCommandExecutor_IsModuleEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// IsPackageInstalled provides a mock function with given fields: dir, packageToCheck
func (_m *MockCommandExecutor) IsPackageInstalled(dir string, packageToCheck string) (bool, error) {
	ret := _m.Called(dir, packageToCheck)

	if len(ret) == 0 {
		panic("no return value specified for IsPackageInstalled")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return rf(dir, packageToCheck)
	}
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(dir, packageToCheck)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(dir, packageToCheck)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandExecutor_IsPackageInstalled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsPackageInstalled'
type MockCommandExecutor_IsPackageInstalled_Call struct {
	*mock.Call
}

// IsPackageInstalled is a helper method to define mock.On call
//   - dir string
//   - packageToCheck string
func (_e *MockCommandExecutor_Expecter) IsPackageInstalled(dir interface{}, packageToCheck interface{}) *MockCommandExecutor_IsPackageInstalled_Call {
	return &MockCommandExecutor_IsPackageInstalled_Call{Call: _e.mock.On("IsPackageInstalled", dir, packageToCheck)}
}

func (_c *MockCommandExecutor_IsPackageInstalled_Call) Run(run func(dir string, packageToCheck string)) *MockCommandExecutor_IsPackageInstalled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockCommandExecutor_IsPackageInstalled_Call) Return(_a0 bool, _a1 error) *MockCommandExecutor_IsPackageInstalled_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandExecutor_IsPackageInstalled_Call) RunAndReturn(run func(string, string) (bool, error)) *MockCommandExecutor_IsPackageInstalled_Call {
	_c.Call.Return(run)
	return _c
}

// LocalizeTranslations provides a mock function with given fields: dir, site
func (_m *MockCommandExecutor) LocalizeTranslations(dir string, site string) error {
	ret := _m.Called(dir, site)

	if len(ret) == 0 {
		panic("no return value specified for LocalizeTranslations")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(dir, site)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommandExecutor_LocalizeTranslations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LocalizeTranslations'
type MockCommandExecutor_LocalizeTranslations_Call struct {
	*mock.Call
}

// LocalizeTranslations is a helper method to define mock.On call
//   - dir string
//   - site string
func (_e *MockCommandExecutor_Expecter) LocalizeTranslations(dir interface{}, site interface{}) *MockCommandExecutor_LocalizeTranslations_Call {
	return &MockCommandExecutor_LocalizeTranslations_Call{Call: _e.mock.On("LocalizeTranslations", dir, site)}
}

func (_c *MockCommandExecutor_LocalizeTranslations_Call) Run(run func(dir string, site string)) *MockCommandExecutor_LocalizeTranslations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockCommandExecutor_LocalizeTranslations_Call) Return(_a0 error) *MockCommandExecutor_LocalizeTranslations_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommandExecutor_LocalizeTranslations_Call) RunAndReturn(run func(string, string) error) *MockCommandExecutor_LocalizeTranslations_Call {
	_c.Call.Return(run)
	return _c
}

// RemovePackages provides a mock function with given fields: dir, packages
func (_m *MockCommandExecutor) RemovePackages(dir string, packages ...string) (string, error) {
	_va := make([]interface{}, len(packages))
	for _i := range packages {
		_va[_i] = packages[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, dir)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RemovePackages")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, ...string) (string, error)); ok {
		return rf(dir, packages...)
	}
	if rf, ok := ret.Get(0).(func(string, ...string) string); ok {
		r0 = rf(dir, packages...)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, ...string) error); ok {
		r1 = rf(dir, packages...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandExecutor_RemovePackages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemovePackages'
type MockCommandExecutor_RemovePackages_Call struct {
	*mock.Call
}

// RemovePackages is a helper method to define mock.On call
//   - dir string
//   - packages ...string
func (_e *MockCommandExecutor_Expecter) RemovePackages(dir interface{}, packages ...interface{}) *MockCommandExecutor_RemovePackages_Call {
	return &MockCommandExecutor_RemovePackages_Call{Call: _e.mock.On("RemovePackages",
		append([]interface{}{dir}, packages...)...)}
}

func (_c *MockCommandExecutor_RemovePackages_Call) Run(run func(dir string, packages ...string)) *MockCommandExecutor_RemovePackages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockCommandExecutor_RemovePackages_Call) Return(_a0 string, _a1 error) *MockCommandExecutor_RemovePackages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandExecutor_RemovePackages_Call) RunAndReturn(run func(string, ...string) (string, error)) *MockCommandExecutor_RemovePackages_Call {
	_c.Call.Return(run)
	return _c
}

// RunPHPCBF provides a mock function with given fields: dir
func (_m *MockCommandExecutor) RunPHPCBF(dir string) error {
	ret := _m.Called(dir)

	if len(ret) == 0 {
		panic("no return value specified for RunPHPCBF")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(dir)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommandExecutor_RunPHPCBF_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunPHPCBF'
type MockCommandExecutor_RunPHPCBF_Call struct {
	*mock.Call
}

// RunPHPCBF is a helper method to define mock.On call
//   - dir string
func (_e *MockCommandExecutor_Expecter) RunPHPCBF(dir interface{}) *MockCommandExecutor_RunPHPCBF_Call {
	return &MockCommandExecutor_RunPHPCBF_Call{Call: _e.mock.On("RunPHPCBF", dir)}
}

func (_c *MockCommandExecutor_RunPHPCBF_Call) Run(run func(dir string)) *MockCommandExecutor_RunPHPCBF_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCommandExecutor_RunPHPCBF_Call) Return(_a0 error) *MockCommandExecutor_RunPHPCBF_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommandExecutor_RunPHPCBF_Call) RunAndReturn(run func(string) error) *MockCommandExecutor_RunPHPCBF_Call {
	_c.Call.Return(run)
	return _c
}

// RunPHPCS provides a mock function with given fields: dir
func (_m *MockCommandExecutor) RunPHPCS(dir string) (string, error) {
	ret := _m.Called(dir)

	if len(ret) == 0 {
		panic("no return value specified for RunPHPCS")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(dir)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(dir)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(dir)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandExecutor_RunPHPCS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunPHPCS'
type MockCommandExecutor_RunPHPCS_Call struct {
	*mock.Call
}

// RunPHPCS is a helper method to define mock.On call
//   - dir string
func (_e *MockCommandExecutor_Expecter) RunPHPCS(dir interface{}) *MockCommandExecutor_RunPHPCS_Call {
	return &MockCommandExecutor_RunPHPCS_Call{Call: _e.mock.On("RunPHPCS", dir)}
}

func (_c *MockCommandExecutor_RunPHPCS_Call) Run(run func(dir string)) *MockCommandExecutor_RunPHPCS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCommandExecutor_RunPHPCS_Call) Return(_a0 string, _a1 error) *MockCommandExecutor_RunPHPCS_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandExecutor_RunPHPCS_Call) RunAndReturn(run func(string) (string, error)) *MockCommandExecutor_RunPHPCS_Call {
	_c.Call.Return(run)
	return _c
}

// RunRector provides a mock function with given fields: dir
func (_m *MockCommandExecutor) RunRector(dir string) (string, error) {
	ret := _m.Called(dir)

	if len(ret) == 0 {
		panic("no return value specified for RunRector")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(dir)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(dir)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(dir)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandExecutor_RunRector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunRector'
type MockCommandExecutor_RunRector_Call struct {
	*mock.Call
}

// RunRector is a helper method to define mock.On call
//   - dir string
func (_e *MockCommandExecutor_Expecter) RunRector(dir interface{}) *MockCommandExecutor_RunRector_Call {
	return &MockCommandExecutor_RunRector_Call{Call: _e.mock.On("RunRector", dir)}
}

func (_c *MockCommandExecutor_RunRector_Call) Run(run func(dir string)) *MockCommandExecutor_RunRector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCommandExecutor_RunRector_Call) Return(_a0 string, _a1 error) *MockCommandExecutor_RunRector_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandExecutor_RunRector_Call) RunAndReturn(run func(string) (string, error)) *MockCommandExecutor_RunRector_Call {
	_c.Call.Return(run)
	return _c
}

// SetComposerAllowPlugins provides a mock function with given fields: dir, plugins
func (_m *MockCommandExecutor) SetComposerAllowPlugins(dir string, plugins map[string]bool) error {
	ret := _m.Called(dir, plugins)

	if len(ret) == 0 {
		panic("no return value specified for SetComposerAllowPlugins")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, map[string]bool) error); ok {
		r0 = rf(dir, plugins)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommandExecutor_SetComposerAllowPlugins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetComposerAllowPlugins'
type MockCommandExecutor_SetComposerAllowPlugins_Call struct {
	*mock.Call
}

// SetComposerAllowPlugins is a helper method to define mock.On call
//   - dir string
//   - plugins map[string]bool
func (_e *MockCommandExecutor_Expecter) SetComposerAllowPlugins(dir interface{}, plugins interface{}) *MockCommandExecutor_SetComposerAllowPlugins_Call {
	return &MockCommandExecutor_SetComposerAllowPlugins_Call{Call: _e.mock.On("SetComposerAllowPlugins", dir, plugins)}
}

func (_c *MockCommandExecutor_SetComposerAllowPlugins_Call) Run(run func(dir string, plugins map[string]bool)) *MockCommandExecutor_SetComposerAllowPlugins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(map[string]bool))
	})
	return _c
}

func (_c *MockCommandExecutor_SetComposerAllowPlugins_Call) Return(_a0 error) *MockCommandExecutor_SetComposerAllowPlugins_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommandExecutor_SetComposerAllowPlugins_Call) RunAndReturn(run func(string, map[string]bool) error) *MockCommandExecutor_SetComposerAllowPlugins_Call {
	_c.Call.Return(run)
	return _c
}

// SetComposerConfig provides a mock function with given fields: dir, key, value
func (_m *MockCommandExecutor) SetComposerConfig(dir string, key string, value string) error {
	ret := _m.Called(dir, key, value)

	if len(ret) == 0 {
		panic("no return value specified for SetComposerConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(dir, key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommandExecutor_SetComposerConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetComposerConfig'
type MockCommandExecutor_SetComposerConfig_Call struct {
	*mock.Call
}

// SetComposerConfig is a helper method to define mock.On call
//   - dir string
//   - key string
//   - value string
func (_e *MockCommandExecutor_Expecter) SetComposerConfig(dir interface{}, key interface{}, value interface{}) *MockCommandExecutor_SetComposerConfig_Call {
	return &MockCommandExecutor_SetComposerConfig_Call{Call: _e.mock.On("SetComposerConfig", dir, key, value)}
}

func (_c *MockCommandExecutor_SetComposerConfig_Call) Run(run func(dir string, key string, value string)) *MockCommandExecutor_SetComposerConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockCommandExecutor_SetComposerConfig_Call) Return(_a0 error) *MockCommandExecutor_SetComposerConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommandExecutor_SetComposerConfig_Call) RunAndReturn(run func(string, string, string) error) *MockCommandExecutor_SetComposerConfig_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateComposerLockHash provides a mock function with given fields: dir
func (_m *MockCommandExecutor) UpdateComposerLockHash(dir string) error {
	ret := _m.Called(dir)

	if len(ret) == 0 {
		panic("no return value specified for UpdateComposerLockHash")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(dir)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommandExecutor_UpdateComposerLockHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateComposerLockHash'
type MockCommandExecutor_UpdateComposerLockHash_Call struct {
	*mock.Call
}

// UpdateComposerLockHash is a helper method to define mock.On call
//   - dir string
func (_e *MockCommandExecutor_Expecter) UpdateComposerLockHash(dir interface{}) *MockCommandExecutor_UpdateComposerLockHash_Call {
	return &MockCommandExecutor_UpdateComposerLockHash_Call{Call: _e.mock.On("UpdateComposerLockHash", dir)}
}

func (_c *MockCommandExecutor_UpdateComposerLockHash_Call) Run(run func(dir string)) *MockCommandExecutor_UpdateComposerLockHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCommandExecutor_UpdateComposerLockHash_Call) Return(_a0 error) *MockCommandExecutor_UpdateComposerLockHash_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommandExecutor_UpdateComposerLockHash_Call) RunAndReturn(run func(string) error) *MockCommandExecutor_UpdateComposerLockHash_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDependencies provides a mock function with given fields: dir, packagesToUpdate, minimalChanges, dryRun
func (_m *MockCommandExecutor) UpdateDependencies(dir string, packagesToUpdate []string, minimalChanges bool, dryRun bool) (string, error) {
	ret := _m.Called(dir, packagesToUpdate, minimalChanges, dryRun)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDependencies")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, []string, bool, bool) (string, error)); ok {
		return rf(dir, packagesToUpdate, minimalChanges, dryRun)
	}
	if rf, ok := ret.Get(0).(func(string, []string, bool, bool) string); ok {
		r0 = rf(dir, packagesToUpdate, minimalChanges, dryRun)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, []string, bool, bool) error); ok {
		r1 = rf(dir, packagesToUpdate, minimalChanges, dryRun)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandExecutor_UpdateDependencies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDependencies'
type MockCommandExecutor_UpdateDependencies_Call struct {
	*mock.Call
}

// UpdateDependencies is a helper method to define mock.On call
//   - dir string
//   - packagesToUpdate []string
//   - minimalChanges bool
//   - dryRun bool
func (_e *MockCommandExecutor_Expecter) UpdateDependencies(dir interface{}, packagesToUpdate interface{}, minimalChanges interface{}, dryRun interface{}) *MockCommandExecutor_UpdateDependencies_Call {
	return &MockCommandExecutor_UpdateDependencies_Call{Call: _e.mock.On("UpdateDependencies", dir, packagesToUpdate, minimalChanges, dryRun)}
}

func (_c *MockCommandExecutor_UpdateDependencies_Call) Run(run func(dir string, packagesToUpdate []string, minimalChanges bool, dryRun bool)) *MockCommandExecutor_UpdateDependencies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]string), args[2].(bool), args[3].(bool))
	})
	return _c
}

func (_c *MockCommandExecutor_UpdateDependencies_Call) Return(_a0 string, _a1 error) *MockCommandExecutor_UpdateDependencies_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandExecutor_UpdateDependencies_Call) RunAndReturn(run func(string, []string, bool, bool) (string, error)) *MockCommandExecutor_UpdateDependencies_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSite provides a mock function with given fields: dir, site
func (_m *MockCommandExecutor) UpdateSite(dir string, site string) error {
	ret := _m.Called(dir, site)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(dir, site)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommandExecutor_UpdateSite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSite'
type MockCommandExecutor_UpdateSite_Call struct {
	*mock.Call
}

// UpdateSite is a helper method to define mock.On call
//   - dir string
//   - site string
func (_e *MockCommandExecutor_Expecter) UpdateSite(dir interface{}, site interface{}) *MockCommandExecutor_UpdateSite_Call {
	return &MockCommandExecutor_UpdateSite_Call{Call: _e.mock.On("UpdateSite", dir, site)}
}

func (_c *MockCommandExecutor_UpdateSite_Call) Run(run func(dir string, site string)) *MockCommandExecutor_UpdateSite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockCommandExecutor_UpdateSite_Call) Return(_a0 error) *MockCommandExecutor_UpdateSite_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommandExecutor_UpdateSite_Call) RunAndReturn(run func(string, string) error) *MockCommandExecutor_UpdateSite_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCommandExecutor creates a new instance of MockCommandExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommandExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommandExecutor {
	mock := &MockCommandExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
