// Code generated by mockery v2.53.3. DO NOT EDIT.

package utils

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCommandExecutor is an autogenerated mock type for the CommandExecutor type
type MockCommandExecutor struct {
	mock.Mock
}

type MockCommandExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommandExecutor) EXPECT() *MockCommandExecutor_Expecter {
	return &MockCommandExecutor_Expecter{mock: &_m.Mock}
}

// ConfigResave provides a mock function with given fields: ctx, dir, site
func (_m *MockCommandExecutor) ConfigResave(ctx context.Context, dir string, site string) error {
	ret := _m.Called(ctx, dir, site)

	if len(ret) == 0 {
		panic("no return value specified for ConfigResave")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, dir, site)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommandExecutor_ConfigResave_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfigResave'
type MockCommandExecutor_ConfigResave_Call struct {
	*mock.Call
}

// ConfigResave is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - site string
func (_e *MockCommandExecutor_Expecter) ConfigResave(ctx interface{}, dir interface{}, site interface{}) *MockCommandExecutor_ConfigResave_Call {
	return &MockCommandExecutor_ConfigResave_Call{Call: _e.mock.On("ConfigResave", ctx, dir, site)}
}

func (_c *MockCommandExecutor_ConfigResave_Call) Run(run func(ctx context.Context, dir string, site string)) *MockCommandExecutor_ConfigResave_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockCommandExecutor_ConfigResave_Call) Return(_a0 error) *MockCommandExecutor_ConfigResave_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommandExecutor_ConfigResave_Call) RunAndReturn(run func(context.Context, string, string) error) *MockCommandExecutor_ConfigResave_Call {
	_c.Call.Return(run)
	return _c
}

// ExecComposer provides a mock function with given fields: ctx, dir, args
func (_m *MockCommandExecutor) ExecComposer(ctx context.Context, dir string, args ...string) (string, error) {
	_va := make([]interface{}, len(args))
	for _i := range args {
		_va[_i] = args[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, dir)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExecComposer")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...string) (string, error)); ok {
		return rf(ctx, dir, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...string) string); ok {
		r0 = rf(ctx, dir, args...)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...string) error); ok {
		r1 = rf(ctx, dir, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandExecutor_ExecComposer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecComposer'
type MockCommandExecutor_ExecComposer_Call struct {
	*mock.Call
}

// ExecComposer is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - args ...string
func (_e *MockCommandExecutor_Expecter) ExecComposer(ctx interface{}, dir interface{}, args ...interface{}) *MockCommandExecutor_ExecComposer_Call {
	return &MockCommandExecutor_ExecComposer_Call{Call: _e.mock.On("ExecComposer",
		append([]interface{}{ctx, dir}, args...)...)}
}

func (_c *MockCommandExecutor_ExecComposer_Call) Run(run func(ctx context.Context, dir string, args ...string)) *MockCommandExecutor_ExecComposer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockCommandExecutor_ExecComposer_Call) Return(_a0 string, _a1 error) *MockCommandExecutor_ExecComposer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandExecutor_ExecComposer_Call) RunAndReturn(run func(context.Context, string, ...string) (string, error)) *MockCommandExecutor_ExecComposer_Call {
	_c.Call.Return(run)
	return _c
}

// ExecDrush provides a mock function with given fields: ctx, dir, site, args
func (_m *MockCommandExecutor) ExecDrush(ctx context.Context, dir string, site string, args ...string) (string, error) {
	_va := make([]interface{}, len(args))
	for _i := range args {
		_va[_i] = args[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, dir, site)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExecDrush")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...string) (string, error)); ok {
		return rf(ctx, dir, site, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...string) string); ok {
		r0 = rf(ctx, dir, site, args...)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, ...string) error); ok {
		r1 = rf(ctx, dir, site, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandExecutor_ExecDrush_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecDrush'
type MockCommandExecutor_ExecDrush_Call struct {
	*mock.Call
}

// ExecDrush is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - site string
//   - args ...string
func (_e *MockCommandExecutor_Expecter) ExecDrush(ctx interface{}, dir interface{}, site interface{}, args ...interface{}) *MockCommandExecutor_ExecDrush_Call {
	return &MockCommandExecutor_ExecDrush_Call{Call: _e.mock.On("ExecDrush",
		append([]interface{}{ctx, dir, site}, args...)...)}
}

func (_c *MockCommandExecutor_ExecDrush_Call) Run(run func(ctx context.Context, dir string, site string, args ...string)) *MockCommandExecutor_ExecDrush_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockCommandExecutor_ExecDrush_Call) Return(_a0 string, _a1 error) *MockCommandExecutor_ExecDrush_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandExecutor_ExecDrush_Call) RunAndReturn(run func(context.Context, string, string, ...string) (string, error)) *MockCommandExecutor_ExecDrush_Call {
	_c.Call.Return(run)
	return _c
}

// ExportConfiguration provides a mock function with given fields: ctx, dir, site
func (_m *MockCommandExecutor) ExportConfiguration(ctx context.Context, dir string, site string) error {
	ret := _m.Called(ctx, dir, site)

	if len(ret) == 0 {
		panic("no return value specified for ExportConfiguration")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, dir, site)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommandExecutor_ExportConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportConfiguration'
type MockCommandExecutor_ExportConfiguration_Call struct {
	*mock.Call
}

// ExportConfiguration is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - site string
func (_e *MockCommandExecutor_Expecter) ExportConfiguration(ctx interface{}, dir interface{}, site interface{}) *MockCommandExecutor_ExportConfiguration_Call {
	return &MockCommandExecutor_ExportConfiguration_Call{Call: _e.mock.On("ExportConfiguration", ctx, dir, site)}
}

func (_c *MockCommandExecutor_ExportConfiguration_Call) Run(run func(ctx context.Context, dir string, site string)) *MockCommandExecutor_ExportConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockCommandExecutor_ExportConfiguration_Call) Return(_a0 error) *MockCommandExecutor_ExportConfiguration_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommandExecutor_ExportConfiguration_Call) RunAndReturn(run func(context.Context, string, string) error) *MockCommandExecutor_ExportConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateDiffTable provides a mock function with given fields: ctx, path, targetBranch, withLinks
func (_m *MockCommandExecutor) GenerateDiffTable(ctx context.Context, path string, targetBranch string, withLinks bool) (string, error) {
	ret := _m.Called(ctx, path, targetBranch, withLinks)

	if len(ret) == 0 {
		panic("no return value specified for GenerateDiffTable")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) (string, error)); ok {
		return rf(ctx, path, targetBranch, withLinks)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) string); ok {
		r0 = rf(ctx, path, targetBranch, withLinks)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = rf(ctx, path, targetBranch, withLinks)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandExecutor_GenerateDiffTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateDiffTable'
type MockCommandExecutor_GenerateDiffTable_Call struct {
	*mock.Call
}

// GenerateDiffTable is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - targetBranch string
//   - withLinks bool
func (_e *MockCommandExecutor_Expecter) GenerateDiffTable(ctx interface{}, path interface{}, targetBranch interface{}, withLinks interface{}) *MockCommandExecutor_GenerateDiffTable_Call {
	return &MockCommandExecutor_GenerateDiffTable_Call{Call: _e.mock.On("GenerateDiffTable", ctx, path, targetBranch, withLinks)}
}

func (_c *MockCommandExecutor_GenerateDiffTable_Call) Run(run func(ctx context.Context, path string, targetBranch string, withLinks bool)) *MockCommandExecutor_GenerateDiffTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockCommandExecutor_GenerateDiffTable_Call) Return(_a0 string, _a1 error) *MockCommandExecutor_GenerateDiffTable_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandExecutor_GenerateDiffTable_Call) RunAndReturn(run func(context.Context, string, string, bool) (string, error)) *MockCommandExecutor_GenerateDiffTable_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfigSyncDir provides a mock function with given fields: ctx, dir, site, relative
func (_m *MockCommandExecutor) GetConfigSyncDir(ctx context.Context, dir string, site string, relative bool) (string, error) {
	ret := _m.Called(ctx, dir, site, relative)

	if len(ret) == 0 {
		panic("no return value specified for GetConfigSyncDir")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) (string, error)); ok {
		return rf(ctx, dir, site, relative)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) string); ok {
		r0 = rf(ctx, dir, site, relative)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = rf(ctx, dir, site, relative)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandExecutor_GetConfigSyncDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfigSyncDir'
type MockCommandExecutor_GetConfigSyncDir_Call struct {
	*mock.Call
}

// GetConfigSyncDir is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - site string
//   - relative bool
func (_e *MockCommandExecutor_Expecter) GetConfigSyncDir(ctx interface{}, dir interface{}, site interface{}, relative interface{}) *MockCommandExecutor_GetConfigSyncDir_Call {
	return &MockCommandExecutor_GetConfigSyncDir_Call{Call: _e.mock.On("GetConfigSyncDir", ctx, dir, site, relative)}
}

func (_c *MockCommandExecutor_GetConfigSyncDir_Call) Run(run func(ctx context.Context, dir string, site string, relative bool)) *MockCommandExecutor_GetConfigSyncDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockCommandExecutor_GetConfigSyncDir_Call) Return(_a0 string, _a1 error) *MockCommandExecutor_GetConfigSyncDir_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandExecutor_GetConfigSyncDir_Call) RunAndReturn(run func(context.Context, string, string, bool) (string, error)) *MockCommandExecutor_GetConfigSyncDir_Call {
	_c.Call.Return(run)
	return _c
}

// GetCustomCodeDirectories provides a mock function with given fields: ctx, dir
func (_m *MockCommandExecutor) GetCustomCodeDirectories(ctx context.Context, dir string) ([]string, error) {
	ret := _m.Called(ctx, dir)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomCodeDirectories")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, dir)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, dir)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, dir)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandExecutor_GetCustomCodeDirectories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCustomCodeDirectories'
type MockCommandExecutor_GetCustomCodeDirectories_Call struct {
	*mock.Call
}

// GetCustomCodeDirectories is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
func (_e *MockCommandExecutor_Expecter) GetCustomCodeDirectories(ctx interface{}, dir interface{}) *MockCommandExecutor_GetCustomCodeDirectories_Call {
	return &MockCommandExecutor_GetCustomCodeDirectories_Call{Call: _e.mock.On("GetCustomCodeDirectories", ctx, dir)}
}

func (_c *MockCommandExecutor_GetCustomCodeDirectories_Call) Run(run func(ctx context.Context, dir string)) *MockCommandExecutor_GetCustomCodeDirectories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCommandExecutor_GetCustomCodeDirectories_Call) Return(_a0 []string, _a1 error) *MockCommandExecutor_GetCustomCodeDirectories_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandExecutor_GetCustomCodeDirectories_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *MockCommandExecutor_GetCustomCodeDirectories_Call {
	_c.Call.Return(run)
	return _c
}

// GetDrupalWebDir provides a mock function with given fields: ctx, dir
func (_m *MockCommandExecutor) GetDrupalWebDir(ctx context.Context, dir string) (string, error) {
	ret := _m.Called(ctx, dir)

	if len(ret) == 0 {
		panic("no return value specified for GetDrupalWebDir")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, dir)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, dir)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, dir)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandExecutor_GetDrupalWebDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDrupalWebDir'
type MockCommandExecutor_GetDrupalWebDir_Call struct {
	*mock.Call
}

// GetDrupalWebDir is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
func (_e *MockCommandExecutor_Expecter) GetDrupalWebDir(ctx interface{}, dir interface{}) *MockCommandExecutor_GetDrupalWebDir_Call {
	return &MockCommandExecutor_GetDrupalWebDir_Call{Call: _e.mock.On("GetDrupalWebDir", ctx, dir)}
}

func (_c *MockCommandExecutor_GetDrupalWebDir_Call) Run(run func(ctx context.Context, dir string)) *MockCommandExecutor_GetDrupalWebDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCommandExecutor_GetDrupalWebDir_Call) Return(_a0 string, _a1 error) *MockCommandExecutor_GetDrupalWebDir_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandExecutor_GetDrupalWebDir_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockCommandExecutor_GetDrupalWebDir_Call {
	_c.Call.Return(run)
	return _c
}

// GetTranslationPath provides a mock function with given fields: ctx, dir, site, relative
func (_m *MockCommandExecutor) GetTranslationPath(ctx context.Context, dir string, site string, relative bool) (string, error) {
	ret := _m.Called(ctx, dir, site, relative)

	if len(ret) == 0 {
		panic("no return value specified for GetTranslationPath")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) (string, error)); ok {
		return rf(ctx, dir, site, relative)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) string); ok {
		r0 = rf(ctx, dir, site, relative)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = rf(ctx, dir, site, relative)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandExecutor_GetTranslationPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTranslationPath'
type MockCommandExecutor_GetTranslationPath_Call struct {
	*mock.Call
}

// GetTranslationPath is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - site string
//   - relative bool
func (_e *MockCommandExecutor_Expecter) GetTranslationPath(ctx interface{}, dir interface{}, site interface{}, relative interface{}) *MockCommandExecutor_GetTranslationPath_Call {
	return &MockCommandExecutor_GetTranslationPath_Call{Call: _e.mock.On("GetTranslationPath", ctx, dir, site, relative)}
}

func (_c *MockCommandExecutor_GetTranslationPath_Call) Run(run func(ctx context.Context, dir string, site string, relative bool)) *MockCommandExecutor_GetTranslationPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockCommandExecutor_GetTranslationPath_Call) Return(_a0 string, _a1 error) *MockCommandExecutor_GetTranslationPath_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandExecutor_GetTranslationPath_Call) RunAndReturn(run func(context.Context, string, string, bool) (string, error)) *MockCommandExecutor_GetTranslationPath_Call {
	_c.Call.Return(run)
	return _c
}

// InstallSite provides a mock function with given fields: ctx, dir, site
func (_m *MockCommandExecutor) InstallSite(ctx context.Context, dir string, site string) error {
	ret := _m.Called(ctx, dir, site)

	if len(ret) == 0 {
		panic("no return value specified for InstallSite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, dir, site)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommandExecutor_InstallSite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallSite'
type MockCommandExecutor_InstallSite_Call struct {
	*mock.Call
}

// InstallSite is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - site string
func (_e *MockCommandExecutor_Expecter) InstallSite(ctx interface{}, dir interface{}, site interface{}) *MockCommandExecutor_InstallSite_Call {
	return &MockCommandExecutor_InstallSite_Call{Call: _e.mock.On("InstallSite", ctx, dir, site)}
}

func (_c *MockCommandExecutor_InstallSite_Call) Run(run func(ctx context.Context, dir string, site string)) *MockCommandExecutor_InstallSite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockCommandExecutor_InstallSite_Call) Return(_a0 error) *MockCommandExecutor_InstallSite_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommandExecutor_InstallSite_Call) RunAndReturn(run func(context.Context, string, string) error) *MockCommandExecutor_InstallSite_Call {
	_c.Call.Return(run)
	return _c
}

// IsModuleEnabled provides a mock function with given fields: ctx, dir, site, module
func (_m *MockCommandExecutor) IsModuleEnabled(ctx context.Context, dir string, site string, module string) (bool, error) {
	ret := _m.Called(ctx, dir, site, module)

	if len(ret) == 0 {
		panic("no return value specified for IsModuleEnabled")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (bool, error)); ok {
		return rf(ctx, dir, site, module)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) bool); ok {
		r0 = rf(ctx, dir, site, module)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, dir, site, module)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandExecutor_IsModuleEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsModuleEnabled'
type MockCommandExecutor_IsModuleEnabled_Call struct {
	*mock.Call
}

// IsModuleEnabled is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - site string
//   - module string
func (_e *MockCommandExecutor_Expecter) IsModuleEnabled(ctx interface{}, dir interface{}, site interface{}, module interface{}) *MockCommandExecutor_IsModuleEnabled_Call {
	return &MockCommandExecutor_IsModuleEnabled_Call{Call: _e.mock.On("IsModuleEnabled", ctx, dir, site, module)}
}

func (_c *MockCommandExecutor_IsModuleEnabled_Call) Run(run func(ctx context.Context, dir string, site string, module string)) *MockCommandExecutor_IsModuleEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockCommandExecutor_IsModuleEnabled_Call) Return(_a0 bool, _a1 error) *MockCommandExecutor_IsModuleEnabled_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandExecutor_IsModuleEnabled_Call) RunAndReturn(run func(context.Context, string, string, string) (bool, error)) *MockCommandExecutor_IsModuleEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// LocalizeTranslations provides a mock function with given fields: ctx, dir, site
func (_m *MockCommandExecutor) LocalizeTranslations(ctx context.Context, dir string, site string) error {
	ret := _m.Called(ctx, dir, site)

	if len(ret) == 0 {
		panic("no return value specified for LocalizeTranslations")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, dir, site)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommandExecutor_LocalizeTranslations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LocalizeTranslations'
type MockCommandExecutor_LocalizeTranslations_Call struct {
	*mock.Call
}

// LocalizeTranslations is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - site string
func (_e *MockCommandExecutor_Expecter) LocalizeTranslations(ctx interface{}, dir interface{}, site interface{}) *MockCommandExecutor_LocalizeTranslations_Call {
	return &MockCommandExecutor_LocalizeTranslations_Call{Call: _e.mock.On("LocalizeTranslations", ctx, dir, site)}
}

func (_c *MockCommandExecutor_LocalizeTranslations_Call) Run(run func(ctx context.Context, dir string, site string)) *MockCommandExecutor_LocalizeTranslations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockCommandExecutor_LocalizeTranslations_Call) Return(_a0 error) *MockCommandExecutor_LocalizeTranslations_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommandExecutor_LocalizeTranslations_Call) RunAndReturn(run func(context.Context, string, string) error) *MockCommandExecutor_LocalizeTranslations_Call {
	_c.Call.Return(run)
	return _c
}

// RunPHPCBF provides a mock function with given fields: ctx, dir
func (_m *MockCommandExecutor) RunPHPCBF(ctx context.Context, dir string) error {
	ret := _m.Called(ctx, dir)

	if len(ret) == 0 {
		panic("no return value specified for RunPHPCBF")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, dir)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommandExecutor_RunPHPCBF_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunPHPCBF'
type MockCommandExecutor_RunPHPCBF_Call struct {
	*mock.Call
}

// RunPHPCBF is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
func (_e *MockCommandExecutor_Expecter) RunPHPCBF(ctx interface{}, dir interface{}) *MockCommandExecutor_RunPHPCBF_Call {
	return &MockCommandExecutor_RunPHPCBF_Call{Call: _e.mock.On("RunPHPCBF", ctx, dir)}
}

func (_c *MockCommandExecutor_RunPHPCBF_Call) Run(run func(ctx context.Context, dir string)) *MockCommandExecutor_RunPHPCBF_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCommandExecutor_RunPHPCBF_Call) Return(_a0 error) *MockCommandExecutor_RunPHPCBF_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommandExecutor_RunPHPCBF_Call) RunAndReturn(run func(context.Context, string) error) *MockCommandExecutor_RunPHPCBF_Call {
	_c.Call.Return(run)
	return _c
}

// RunPHPCS provides a mock function with given fields: ctx, dir
func (_m *MockCommandExecutor) RunPHPCS(ctx context.Context, dir string) (string, error) {
	ret := _m.Called(ctx, dir)

	if len(ret) == 0 {
		panic("no return value specified for RunPHPCS")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, dir)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, dir)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, dir)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandExecutor_RunPHPCS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunPHPCS'
type MockCommandExecutor_RunPHPCS_Call struct {
	*mock.Call
}

// RunPHPCS is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
func (_e *MockCommandExecutor_Expecter) RunPHPCS(ctx interface{}, dir interface{}) *MockCommandExecutor_RunPHPCS_Call {
	return &MockCommandExecutor_RunPHPCS_Call{Call: _e.mock.On("RunPHPCS", ctx, dir)}
}

func (_c *MockCommandExecutor_RunPHPCS_Call) Run(run func(ctx context.Context, dir string)) *MockCommandExecutor_RunPHPCS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCommandExecutor_RunPHPCS_Call) Return(_a0 string, _a1 error) *MockCommandExecutor_RunPHPCS_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandExecutor_RunPHPCS_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockCommandExecutor_RunPHPCS_Call {
	_c.Call.Return(run)
	return _c
}

// RunRector provides a mock function with given fields: ctx, dir
func (_m *MockCommandExecutor) RunRector(ctx context.Context, dir string) (string, error) {
	ret := _m.Called(ctx, dir)

	if len(ret) == 0 {
		panic("no return value specified for RunRector")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, dir)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, dir)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, dir)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandExecutor_RunRector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunRector'
type MockCommandExecutor_RunRector_Call struct {
	*mock.Call
}

// RunRector is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
func (_e *MockCommandExecutor_Expecter) RunRector(ctx interface{}, dir interface{}) *MockCommandExecutor_RunRector_Call {
	return &MockCommandExecutor_RunRector_Call{Call: _e.mock.On("RunRector", ctx, dir)}
}

func (_c *MockCommandExecutor_RunRector_Call) Run(run func(ctx context.Context, dir string)) *MockCommandExecutor_RunRector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCommandExecutor_RunRector_Call) Return(_a0 string, _a1 error) *MockCommandExecutor_RunRector_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandExecutor_RunRector_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockCommandExecutor_RunRector_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateComposerLockHash provides a mock function with given fields: ctx, dir
func (_m *MockCommandExecutor) UpdateComposerLockHash(ctx context.Context, dir string) error {
	ret := _m.Called(ctx, dir)

	if len(ret) == 0 {
		panic("no return value specified for UpdateComposerLockHash")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, dir)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommandExecutor_UpdateComposerLockHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateComposerLockHash'
type MockCommandExecutor_UpdateComposerLockHash_Call struct {
	*mock.Call
}

// UpdateComposerLockHash is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
func (_e *MockCommandExecutor_Expecter) UpdateComposerLockHash(ctx interface{}, dir interface{}) *MockCommandExecutor_UpdateComposerLockHash_Call {
	return &MockCommandExecutor_UpdateComposerLockHash_Call{Call: _e.mock.On("UpdateComposerLockHash", ctx, dir)}
}

func (_c *MockCommandExecutor_UpdateComposerLockHash_Call) Run(run func(ctx context.Context, dir string)) *MockCommandExecutor_UpdateComposerLockHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCommandExecutor_UpdateComposerLockHash_Call) Return(_a0 error) *MockCommandExecutor_UpdateComposerLockHash_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommandExecutor_UpdateComposerLockHash_Call) RunAndReturn(run func(context.Context, string) error) *MockCommandExecutor_UpdateComposerLockHash_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSite provides a mock function with given fields: ctx, dir, site
func (_m *MockCommandExecutor) UpdateSite(ctx context.Context, dir string, site string) error {
	ret := _m.Called(ctx, dir, site)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, dir, site)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommandExecutor_UpdateSite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSite'
type MockCommandExecutor_UpdateSite_Call struct {
	*mock.Call
}

// UpdateSite is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - site string
func (_e *MockCommandExecutor_Expecter) UpdateSite(ctx interface{}, dir interface{}, site interface{}) *MockCommandExecutor_UpdateSite_Call {
	return &MockCommandExecutor_UpdateSite_Call{Call: _e.mock.On("UpdateSite", ctx, dir, site)}
}

func (_c *MockCommandExecutor_UpdateSite_Call) Run(run func(ctx context.Context, dir string, site string)) *MockCommandExecutor_UpdateSite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockCommandExecutor_UpdateSite_Call) Return(_a0 error) *MockCommandExecutor_UpdateSite_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommandExecutor_UpdateSite_Call) RunAndReturn(run func(context.Context, string, string) error) *MockCommandExecutor_UpdateSite_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCommandExecutor creates a new instance of MockCommandExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommandExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommandExecutor {
	mock := &MockCommandExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
