// Code generated by mockery v2.51.1. DO NOT EDIT.

package internal

import (
	git "github.com/go-git/go-git/v5"
	mock "github.com/stretchr/testify/mock"

	object "github.com/go-git/go-git/v5/plumbing/object"

	plumbing "github.com/go-git/go-git/v5/plumbing"

	storer "github.com/go-git/go-git/v5/plumbing/storer"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CommitObject provides a mock function with given fields: h
func (_m *MockRepository) CommitObject(h plumbing.Hash) (*object.Commit, error) {
	ret := _m.Called(h)

	if len(ret) == 0 {
		panic("no return value specified for CommitObject")
	}

	var r0 *object.Commit
	var r1 error
	if rf, ok := ret.Get(0).(func(plumbing.Hash) (*object.Commit, error)); ok {
		return rf(h)
	}
	if rf, ok := ret.Get(0).(func(plumbing.Hash) *object.Commit); ok {
		r0 = rf(h)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*object.Commit)
		}
	}

	if rf, ok := ret.Get(1).(func(plumbing.Hash) error); ok {
		r1 = rf(h)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CommitObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitObject'
type MockRepository_CommitObject_Call struct {
	*mock.Call
}

// CommitObject is a helper method to define mock.On call
//   - h plumbing.Hash
func (_e *MockRepository_Expecter) CommitObject(h interface{}) *MockRepository_CommitObject_Call {
	return &MockRepository_CommitObject_Call{Call: _e.mock.On("CommitObject", h)}
}

func (_c *MockRepository_CommitObject_Call) Run(run func(h plumbing.Hash)) *MockRepository_CommitObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(plumbing.Hash))
	})
	return _c
}

func (_c *MockRepository_CommitObject_Call) Return(_a0 *object.Commit, _a1 error) *MockRepository_CommitObject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CommitObject_Call) RunAndReturn(run func(plumbing.Hash) (*object.Commit, error)) *MockRepository_CommitObject_Call {
	_c.Call.Return(run)
	return _c
}

// Head provides a mock function with no fields
func (_m *MockRepository) Head() (*plumbing.Reference, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Head")
	}

	var r0 *plumbing.Reference
	var r1 error
	if rf, ok := ret.Get(0).(func() (*plumbing.Reference, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *plumbing.Reference); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*plumbing.Reference)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Head_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Head'
type MockRepository_Head_Call struct {
	*mock.Call
}

// Head is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Head() *MockRepository_Head_Call {
	return &MockRepository_Head_Call{Call: _e.mock.On("Head")}
}

func (_c *MockRepository_Head_Call) Run(run func()) *MockRepository_Head_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Head_Call) Return(_a0 *plumbing.Reference, _a1 error) *MockRepository_Head_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Head_Call) RunAndReturn(run func() (*plumbing.Reference, error)) *MockRepository_Head_Call {
	_c.Call.Return(run)
	return _c
}

// Push provides a mock function with given fields: o
func (_m *MockRepository) Push(o *git.PushOptions) error {
	ret := _m.Called(o)

	if len(ret) == 0 {
		panic("no return value specified for Push")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*git.PushOptions) error); ok {
		r0 = rf(o)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Push_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Push'
type MockRepository_Push_Call struct {
	*mock.Call
}

// Push is a helper method to define mock.On call
//   - o *git.PushOptions
func (_e *MockRepository_Expecter) Push(o interface{}) *MockRepository_Push_Call {
	return &MockRepository_Push_Call{Call: _e.mock.On("Push", o)}
}

func (_c *MockRepository_Push_Call) Run(run func(o *git.PushOptions)) *MockRepository_Push_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*git.PushOptions))
	})
	return _c
}

func (_c *MockRepository_Push_Call) Return(_a0 error) *MockRepository_Push_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Push_Call) RunAndReturn(run func(*git.PushOptions) error) *MockRepository_Push_Call {
	_c.Call.Return(run)
	return _c
}

// References provides a mock function with no fields
func (_m *MockRepository) References() (storer.ReferenceIter, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for References")
	}

	var r0 storer.ReferenceIter
	var r1 error
	if rf, ok := ret.Get(0).(func() (storer.ReferenceIter, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() storer.ReferenceIter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(storer.ReferenceIter)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_References_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'References'
type MockRepository_References_Call struct {
	*mock.Call
}

// References is a helper method to define mock.On call
func (_e *MockRepository_Expecter) References() *MockRepository_References_Call {
	return &MockRepository_References_Call{Call: _e.mock.On("References")}
}

func (_c *MockRepository_References_Call) Run(run func()) *MockRepository_References_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_References_Call) Return(_a0 storer.ReferenceIter, _a1 error) *MockRepository_References_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_References_Call) RunAndReturn(run func() (storer.ReferenceIter, error)) *MockRepository_References_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
